[{
	"resource": "/Users/james/Project/jamescompany/jamescompany-backend/app/main.py",
	"owner": "python",
	"severity": 8,
	"message": "식이 필요합니다.",
	"source": "Pylance",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 3,
	"modelVersionId": 222
},{
	"resource": "/Users/james/Project/jamescompany/jamescompany-backend/app/main.py",
	"owner": "python",
	"severity": 8,
	"message": "필요한 모듈 이름",
	"source": "Pylance",
	"startLineNumber": 3,
	"startColumn": 15,
	"endLineNumber": 3,
	"endColumn": 16,
	"modelVersionId": 222
},{
	"resource": "/Users/james/Project/jamescompany/jamescompany-backend/app/main.py",
	"owner": "python",
	"severity": 8,
	"message": "문은 줄 바꿈 또는 세미콜론으로 구분해야 합니다.",
	"source": "Pylance",
	"startLineNumber": 3,
	"startColumn": 15,
	"endLineNumber": 3,
	"endColumn": 16,
	"modelVersionId": 222
},{
	"resource": "/Users/james/Project/jamescompany/jamescompany-backend/app/main.py",
	"owner": "python",
	"severity": 8,
	"message": "문은 줄 바꿈 또는 세미콜론으로 구분해야 합니다.",
	"source": "Pylance",
	"startLineNumber": 3,
	"startColumn": 39,
	"endLineNumber": 3,
	"endColumn": 43,
	"modelVersionId": 222
},{
	"resource": "/Users/james/Project/jamescompany/jamescompany-backend/app/main.py",
	"owner": "python",
	"severity": 8,
	"message": "필요한 모듈 이름",
	"source": "Pylance",
	"startLineNumber": 3,
	"startColumn": 44,
	"endLineNumber": 3,
	"endColumn": 51,
	"modelVersionId": 222
},{
	"resource": "/Users/james/Project/jamescompany/jamescompany-backend/app/main.py",
	"owner": "python",
	"severity": 8,
	"message": "\"import\"가 필요합니다.",
	"source": "Pylance",
	"startLineNumber": 3,
	"startColumn": 44,
	"endLineNumber": 3,
	"endColumn": 51,
	"modelVersionId": 222
},{
	"resource": "/Users/james/Project/jamescompany/jamescompany-backend/app/main.py",
	"owner": "python",
	"severity": 8,
	"message": "문은 줄 바꿈 또는 세미콜론으로 구분해야 합니다.",
	"source": "Pylance",
	"startLineNumber": 3,
	"startColumn": 44,
	"endLineNumber": 3,
	"endColumn": 51,
	"modelVersionId": 222
},{
	"resource": "/Users/james/Project/jamescompany/jamescompany-backend/app/main.py",
	"owner": "python",
	"severity": 8,
	"message": "필요한 모듈 이름",
	"source": "Pylance",
	"startLineNumber": 4,
	"startColumn": 8,
	"endLineNumber": 4,
	"endColumn": 9,
	"modelVersionId": 222
},{
	"resource": "/Users/james/Project/jamescompany/jamescompany-backend/app/main.py",
	"owner": "python",
	"severity": 8,
	"message": "문은 줄 바꿈 또는 세미콜론으로 구분해야 합니다.",
	"source": "Pylance",
	"startLineNumber": 4,
	"startColumn": 8,
	"endLineNumber": 4,
	"endColumn": 9,
	"modelVersionId": 222
},{
	"resource": "/Users/james/Project/jamescompany/jamescompany-backend/app/main.py",
	"owner": "python",
	"severity": 8,
	"message": "문은 줄 바꿈 또는 세미콜론으로 구분해야 합니다.",
	"source": "Pylance",
	"startLineNumber": 4,
	"startColumn": 24,
	"endLineNumber": 4,
	"endColumn": 28,
	"modelVersionId": 222
},{
	"resource": "/Users/james/Project/jamescompany/jamescompany-backend/app/main.py",
	"owner": "python",
	"severity": 8,
	"message": "필요한 모듈 이름",
	"source": "Pylance",
	"startLineNumber": 4,
	"startColumn": 29,
	"endLineNumber": 4,
	"endColumn": 47,
	"modelVersionId": 222
},{
	"resource": "/Users/james/Project/jamescompany/jamescompany-backend/app/main.py",
	"owner": "python",
	"severity": 8,
	"message": "\"import\"가 필요합니다.",
	"source": "Pylance",
	"startLineNumber": 4,
	"startColumn": 29,
	"endLineNumber": 4,
	"endColumn": 47,
	"modelVersionId": 222
},{
	"resource": "/Users/james/Project/jamescompany/jamescompany-backend/app/main.py",
	"owner": "python",
	"severity": 8,
	"message": "문은 줄 바꿈 또는 세미콜론으로 구분해야 합니다.",
	"source": "Pylance",
	"startLineNumber": 4,
	"startColumn": 29,
	"endLineNumber": 4,
	"endColumn": 47,
	"modelVersionId": 222
},{
	"resource": "/Users/james/Project/jamescompany/jamescompany-backend/app/main.py",
	"owner": "python",
	"severity": 8,
	"message": "필요한 모듈 이름",
	"source": "Pylance",
	"startLineNumber": 5,
	"startColumn": 8,
	"endLineNumber": 5,
	"endColumn": 9,
	"modelVersionId": 222
},{
	"resource": "/Users/james/Project/jamescompany/jamescompany-backend/app/main.py",
	"owner": "python",
	"severity": 8,
	"message": "문은 줄 바꿈 또는 세미콜론으로 구분해야 합니다.",
	"source": "Pylance",
	"startLineNumber": 5,
	"startColumn": 8,
	"endLineNumber": 5,
	"endColumn": 9,
	"modelVersionId": 222
},{
	"resource": "/Users/james/Project/jamescompany/jamescompany-backend/app/main.py",
	"owner": "python",
	"severity": 8,
	"message": "문은 줄 바꿈 또는 세미콜론으로 구분해야 합니다.",
	"source": "Pylance",
	"startLineNumber": 5,
	"startColumn": 63,
	"endLineNumber": 5,
	"endColumn": 67,
	"modelVersionId": 222
},{
	"resource": "/Users/james/Project/jamescompany/jamescompany-backend/app/main.py",
	"owner": "python",
	"severity": 8,
	"message": "필요한 모듈 이름",
	"source": "Pylance",
	"startLineNumber": 5,
	"startColumn": 68,
	"endLineNumber": 5,
	"endColumn": 82,
	"modelVersionId": 222
},{
	"resource": "/Users/james/Project/jamescompany/jamescompany-backend/app/main.py",
	"owner": "python",
	"severity": 8,
	"message": "\"import\"가 필요합니다.",
	"source": "Pylance",
	"startLineNumber": 5,
	"startColumn": 68,
	"endLineNumber": 5,
	"endColumn": 82,
	"modelVersionId": 222
},{
	"resource": "/Users/james/Project/jamescompany/jamescompany-backend/app/main.py",
	"owner": "python",
	"severity": 8,
	"message": "문은 줄 바꿈 또는 세미콜론으로 구분해야 합니다.",
	"source": "Pylance",
	"startLineNumber": 5,
	"startColumn": 68,
	"endLineNumber": 5,
	"endColumn": 82,
	"modelVersionId": 222
},{
	"resource": "/Users/james/Project/jamescompany/jamescompany-backend/app/main.py",
	"owner": "python",
	"severity": 8,
	"message": "필요한 모듈 이름",
	"source": "Pylance",
	"startLineNumber": 6,
	"startColumn": 8,
	"endLineNumber": 6,
	"endColumn": 9,
	"modelVersionId": 222
},{
	"resource": "/Users/james/Project/jamescompany/jamescompany-backend/app/main.py",
	"owner": "python",
	"severity": 8,
	"message": "문은 줄 바꿈 또는 세미콜론으로 구분해야 합니다.",
	"source": "Pylance",
	"startLineNumber": 6,
	"startColumn": 8,
	"endLineNumber": 6,
	"endColumn": 9,
	"modelVersionId": 222
},{
	"resource": "/Users/james/Project/jamescompany/jamescompany-backend/app/main.py",
	"owner": "python",
	"severity": 8,
	"message": "문은 줄 바꿈 또는 세미콜론으로 구분해야 합니다.",
	"source": "Pylance",
	"startLineNumber": 6,
	"startColumn": 19,
	"endLineNumber": 6,
	"endColumn": 23,
	"modelVersionId": 222
},{
	"resource": "/Users/james/Project/jamescompany/jamescompany-backend/app/main.py",
	"owner": "python",
	"severity": 8,
	"message": "필요한 모듈 이름",
	"source": "Pylance",
	"startLineNumber": 6,
	"startColumn": 24,
	"endLineNumber": 6,
	"endColumn": 34,
	"modelVersionId": 222
},{
	"resource": "/Users/james/Project/jamescompany/jamescompany-backend/app/main.py",
	"owner": "python",
	"severity": 8,
	"message": "\"import\"가 필요합니다.",
	"source": "Pylance",
	"startLineNumber": 6,
	"startColumn": 24,
	"endLineNumber": 6,
	"endColumn": 34,
	"modelVersionId": 222
},{
	"resource": "/Users/james/Project/jamescompany/jamescompany-backend/app/main.py",
	"owner": "python",
	"severity": 8,
	"message": "문은 줄 바꿈 또는 세미콜론으로 구분해야 합니다.",
	"source": "Pylance",
	"startLineNumber": 6,
	"startColumn": 24,
	"endLineNumber": 6,
	"endColumn": 34,
	"modelVersionId": 222
},{
	"resource": "/Users/james/Project/jamescompany/jamescompany-backend/app/main.py",
	"owner": "python",
	"severity": 8,
	"message": "필요한 모듈 이름",
	"source": "Pylance",
	"startLineNumber": 7,
	"startColumn": 8,
	"endLineNumber": 7,
	"endColumn": 9,
	"modelVersionId": 222
},{
	"resource": "/Users/james/Project/jamescompany/jamescompany-backend/app/main.py",
	"owner": "python",
	"severity": 8,
	"message": "문은 줄 바꿈 또는 세미콜론으로 구분해야 합니다.",
	"source": "Pylance",
	"startLineNumber": 7,
	"startColumn": 8,
	"endLineNumber": 7,
	"endColumn": 9,
	"modelVersionId": 222
},{
	"resource": "/Users/james/Project/jamescompany/jamescompany-backend/app/main.py",
	"owner": "python",
	"severity": 8,
	"message": "문은 줄 바꿈 또는 세미콜론으로 구분해야 합니다.",
	"source": "Pylance",
	"startLineNumber": 7,
	"startColumn": 15,
	"endLineNumber": 7,
	"endColumn": 19,
	"modelVersionId": 222
},{
	"resource": "/Users/james/Project/jamescompany/jamescompany-backend/app/main.py",
	"owner": "python",
	"severity": 8,
	"message": "필요한 모듈 이름",
	"source": "Pylance",
	"startLineNumber": 7,
	"startColumn": 20,
	"endLineNumber": 7,
	"endColumn": 37,
	"modelVersionId": 222
},{
	"resource": "/Users/james/Project/jamescompany/jamescompany-backend/app/main.py",
	"owner": "python",
	"severity": 8,
	"message": "\"import\"가 필요합니다.",
	"source": "Pylance",
	"startLineNumber": 7,
	"startColumn": 20,
	"endLineNumber": 7,
	"endColumn": 37,
	"modelVersionId": 222
},{
	"resource": "/Users/james/Project/jamescompany/jamescompany-backend/app/main.py",
	"owner": "python",
	"severity": 8,
	"message": "문은 줄 바꿈 또는 세미콜론으로 구분해야 합니다.",
	"source": "Pylance",
	"startLineNumber": 7,
	"startColumn": 20,
	"endLineNumber": 7,
	"endColumn": 37,
	"modelVersionId": 222
},{
	"resource": "/Users/james/Project/jamescompany/jamescompany-backend/app/main.py",
	"owner": "python",
	"severity": 8,
	"message": "문은 줄 바꿈 또는 세미콜론으로 구분해야 합니다.",
	"source": "Pylance",
	"startLineNumber": 8,
	"startColumn": 12,
	"endLineNumber": 8,
	"endColumn": 16,
	"modelVersionId": 222
},{
	"resource": "/Users/james/Project/jamescompany/jamescompany-backend/app/main.py",
	"owner": "python",
	"severity": 8,
	"message": "필요한 모듈 이름",
	"source": "Pylance",
	"startLineNumber": 8,
	"startColumn": 17,
	"endLineNumber": 8,
	"endColumn": 37,
	"modelVersionId": 222
},{
	"resource": "/Users/james/Project/jamescompany/jamescompany-backend/app/main.py",
	"owner": "python",
	"severity": 8,
	"message": "\"import\"가 필요합니다.",
	"source": "Pylance",
	"startLineNumber": 8,
	"startColumn": 17,
	"endLineNumber": 8,
	"endColumn": 37,
	"modelVersionId": 222
},{
	"resource": "/Users/james/Project/jamescompany/jamescompany-backend/app/main.py",
	"owner": "python",
	"severity": 8,
	"message": "문은 줄 바꿈 또는 세미콜론으로 구분해야 합니다.",
	"source": "Pylance",
	"startLineNumber": 8,
	"startColumn": 17,
	"endLineNumber": 8,
	"endColumn": 37,
	"modelVersionId": 222
},{
	"resource": "/Users/james/Project/jamescompany/jamescompany-backend/app/main.py",
	"owner": "python",
	"severity": 8,
	"message": "문은 줄 바꿈 또는 세미콜론으로 구분해야 합니다.",
	"source": "Pylance",
	"startLineNumber": 10,
	"startColumn": 11,
	"endLineNumber": 10,
	"endColumn": 18,
	"modelVersionId": 222
},{
	"resource": "/Users/james/Project/jamescompany/jamescompany-backend/app/main.py",
	"owner": "python",
	"severity": 8,
	"message": "문은 줄 바꿈 또는 세미콜론으로 구분해야 합니다.",
	"source": "Pylance",
	"startLineNumber": 10,
	"startColumn": 19,
	"endLineNumber": 10,
	"endColumn": 20,
	"modelVersionId": 222
},{
	"resource": "/Users/james/Project/jamescompany/jamescompany-backend/app/main.py",
	"owner": "python",
	"severity": 8,
	"message": "\"{\"가 닫혀 있지 않습니다.",
	"source": "Pylance",
	"startLineNumber": 10,
	"startColumn": 19,
	"endLineNumber": 10,
	"endColumn": 20,
	"modelVersionId": 222
},{
	"resource": "/Users/james/Project/jamescompany/jamescompany-backend/app/main.py",
	"owner": "python",
	"severity": 8,
	"message": "문은 줄 바꿈 또는 세미콜론으로 구분해야 합니다.",
	"source": "Pylance",
	"startLineNumber": 18,
	"startColumn": 12,
	"endLineNumber": 18,
	"endColumn": 14,
	"modelVersionId": 222
},{
	"resource": "/Users/james/Project/jamescompany/jamescompany-backend/app/main.py",
	"owner": "python",
	"severity": 8,
	"message": "토큰에 잘못된 문자 ‘\\u3f’이(가) 있습니다.",
	"source": "Pylance",
	"startLineNumber": 18,
	"startColumn": 12,
	"endLineNumber": 18,
	"endColumn": 14,
	"modelVersionId": 222
},{
	"resource": "/Users/james/Project/jamescompany/jamescompany-backend/app/main.py",
	"owner": "python",
	"severity": 8,
	"message": "문은 줄 바꿈 또는 세미콜론으로 구분해야 합니다.",
	"source": "Pylance",
	"startLineNumber": 22,
	"startColumn": 7,
	"endLineNumber": 22,
	"endColumn": 17,
	"modelVersionId": 222
},{
	"resource": "/Users/james/Project/jamescompany/jamescompany-backend/app/main.py",
	"owner": "python",
	"severity": 8,
	"message": "문은 줄 바꿈 또는 세미콜론으로 구분해야 합니다.",
	"source": "Pylance",
	"startLineNumber": 22,
	"startColumn": 33,
	"endLineNumber": 22,
	"endColumn": 34,
	"modelVersionId": 222
},{
	"resource": "/Users/james/Project/jamescompany/jamescompany-backend/app/main.py",
	"owner": "python",
	"severity": 8,
	"message": "식이 필요합니다.",
	"source": "Pylance",
	"startLineNumber": 22,
	"startColumn": 33,
	"endLineNumber": 22,
	"endColumn": 34,
	"modelVersionId": 222
},{
	"resource": "/Users/james/Project/jamescompany/jamescompany-backend/app/main.py",
	"owner": "python",
	"severity": 8,
	"message": "문은 줄 바꿈 또는 세미콜론으로 구분해야 합니다.",
	"source": "Pylance",
	"startLineNumber": 297,
	"startColumn": 8,
	"endLineNumber": 297,
	"endColumn": 15,
	"modelVersionId": 222
},{
	"resource": "/Users/james/Project/jamescompany/jamescompany-backend/app/main.py",
	"owner": "python",
	"severity": 8,
	"message": "문은 줄 바꿈 또는 세미콜론으로 구분해야 합니다.",
	"source": "Pylance",
	"startLineNumber": 297,
	"startColumn": 16,
	"endLineNumber": 297,
	"endColumn": 26,
	"modelVersionId": 222
}]